### ISSUE TITLE
Sécurité et traitement des données

### ISSUE THREAD

**Issue by drieu** [lochej/UFREmploidutempsICal4j#1]
Bonjour,

nous envisageons d'utiliser votre application.Nous avons quelques questions en ce qui concerne la sécurité et le traitement des données.
Pouvez-vous me dire comment sont stockées les URLS scannées ? Sont-elles stockées seulement sur le téléphone ?
Conservez vous ou utilisez vous des données personnelles ?

Merci,

**Comment by lochej** [comment]
Bonjour,

L'application UFR emploi du temps stocke l'URL ainsi que le fichier
d'emploi du temps dans le répertoire privé de l'application UFR emploi du
temps.
C'est à dire dans le répertoire donné par l'API Android ->
https://developer.android.com/training/data-storage/files#WriteInternalStorage

Tout simplement le répertoire renvoyé par la fonction getFilesDir(). En
général c'est /data/data/com.jldeveloper.ufremploidutemps/files/ADECal.ics.

L'URL ainsi que les paramètres sont sauvé en tant que fichier de l'API
SharedPreferences d'Android à savoir
/data/data/com.jldeveloper.ufremploidutemps/shared_prefs/com.jldeveloper.ufremploidutemps_preferences.xml

Donc tout ça est dans le répertoire privé de l'application sur le système
de fichier (il faut être rooté pour pouvoir aller traîner dans ces
dossiers...).

Par ailleurs, vous pouvez supprimer l'emploi du temps sauvegardé ainsi que
les paramètres par l'action "supprimer les données" disponible dans les
propriétés de l'appli dans les réglages Android.

Je ne stocke aucune donnée personnelle puisqu'elles ne sont pas nécessaire
au fonctionnement de l'application. Il n'y a ni besoin d'identifiant, ni
besoin de mot de passe... Rien de tout ça.
Les données ne sont stockées que sur le téléphone. Le code source ouvert en
témoigne d'ailleurs.

D'ailleurs, les URL du service ADE sont accessibles sans identifiants ni
mot de passe. Ce qui rend la conception de cette application très basique.

Je reste à votre disposition.

Cordialement,

LOCHE Jérémy



Le mer. 10 oct. 2018 à 09:38, Damien Rieu <notifications@github.com> a
écrit :

**Comment by drieu** [comment]
Merci pour votre réponse.
Pour information, nous allons préconisé cette application pour les utilisateurs ADE à l'université de Limoges (sous réserve de la validation de ma hiérarchie).

Cordialement,
